# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#        (SELECT MAX(SIZE_OF_COLONY) 
#         FROM ECOLI_DATA
#         WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) 
#         - SIZE_OF_COLONY AS YEAR_DEV, 
#         ID
# FROM ECOLI_DATA
# ORDER BY YEAR, YEAR_DEV;

# SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
#        (B.MAXSIZE - A.SIZE_OF_COLONY) AS YEAR_DEV,
#        A.ID
# FROM ECOLI_DATA A
# LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
#            MAX(SIZE_OF_COLONY) AS MAXSIZE
#            FROM ECOLI_DATA 
#            GROUP BY YEAR) AS B
# ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY YEAR, YEAR_DEV;

# WITH MAX_SIZE_OF_COLONY AS (
#     SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
#     FROM ECOLI_DATA
#     GROUP BY YEAR
# )

# SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
#        (M.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
#        E.ID
# FROM ECOLI_DATA E
# LEFT JOIN MAX_SIZE_OF_COLONY M
# ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
# ORDER BY YEAR, YEAR_DEV;

# SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
#        (M.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
#        E.ID
# FROM ECOLI_DATA E, MAX_SIZE_OF_COLONY M
# WHERE YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
# ORDER BY YEAR, YEAR_DEV;
      
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
       B.MAXSIZE - A.SIZE_OF_COLONY AS YEAR_DEV,
       A.ID
FROM ECOLI_DATA A, (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
                           MAX(SIZE_OF_COLONY) AS MAXSIZE
                           FROM ECOLI_DATA
                           GROUP BY YEAR(DIFFERENTIATION_DATE)) B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;